version: "3.9"

services:

  celery_flower:
    restart: always
    build: .
    command: celery -A agent flower --basic_auth=${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}